name: Immortality
version: '${project.version}'
main: dev.bifacial.immortality.Main
api-version: 1.19
authors: [me]
description: A plugin that allows you to revive a dead player by his head.
commands:
  revive:
    description: Revives a Player of your Choosing
    usage: "Usage: /<command> [playername]"
    default: op
    permission: immortality.revive
    permission-message: You do not have permission to use this command.